def fail(message, return_code=1):
    print(message)
    exit(return_code)
